<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260422120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create restaurant table seeded from michelin_my_maps.csv';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE restaurant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, price VARCHAR(32) DEFAULT NULL, cuisine VARCHAR(255) DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, phone_number VARCHAR(64) DEFAULT NULL, url VARCHAR(500) NOT NULL, website_url VARCHAR(500) DEFAULT NULL, award VARCHAR(100) DEFAULT NULL, green_star BOOLEAN NOT NULL, facilities_and_services JSON DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_restaurant_url ON restaurant (url)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE restaurant');
    }
}
